In [1]:
import pandas as pd

In [2]:
# corriger le path
my_df = pd.read_csv('evolution_of_data_analysis.csv', header=0, sep="|")

In [3]:
my_df.shape

(42, 7)

In [4]:
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 7 columns):
Year                                42 non-null int64
Decade                              42 non-null object
Milestone Title                     42 non-null object
Milestone Event                     42 non-null object
Why Important                       42 non-null object
Reference                           39 non-null object
People Process or Technology Tag    42 non-null object
dtypes: int64(1), object(6)
memory usage: 2.4+ KB

In [5]:
my_df.describe()

              Year
count    42.000000
mean   1993.833333
std      18.876901
min    1945.000000
25%    1987.500000
50%    1999.000000
75%    2006.750000
max    2018.000000

In [6]:
my_df.head(2)

,Year,Decade,Milestone Title,Milestone Event,Why Important,Reference,People Process or Technology Tag
0,1945,1940s,ENIAC,First electronic general-purpose computer = ENIAC,Faster decisions using a computer and mathmatics,https://en.wikipedia.org/wiki/ENIAC,Technology
1,1945,1940s,John von Neumann / array,John von Neumann creates a merge sort algorith...,Arrays allow mathmatics| grouping and sorting ...,https://en.wikipedia.org/wiki/John_von_Neumann,People

In [7]:
my_df.tail(2)

,Year,Decade,Milestone Title,Milestone Event,Why Important,Reference,People Process or Technology Tag
40,2015,2010s,Alexa,Amazon Alexa Ecosystem,Making voice to data mainstream and allowing A...,https://www.zdnet.com/article/technology-that-...,Technology
41,2018,2010s,The Data Literacy Project,The Data Literacy Project launches,Building a data driven culture where anyone ca...,https://www.businesswire.com/news/home/2018101...,Process

In [8]:
my_df.sort_index(1)

,Decade,Milestone Event,Milestone Title,People Process or Technology Tag,Reference,Why Important,Year
0,1940s,First electronic general-purpose computer = ENIAC,ENIAC,Technology,https://en.wikipedia.org/wiki/ENIAC,Faster decisions using a computer and mathmatics,1945
1,1940s,John von Neumann creates a merge sort algorith...,John von Neumann / array,People,https://en.wikipedia.org/wiki/John_von_Neumann,Arrays allow mathmatics| grouping and sorting ...,1945
2,1950s,The first computer hard disk used,First Hard Disk,Technology,https://fiftiesweb.com/pop/inventions/,Storing data for reuse = reduces time to recre...,1956
3,1950s,The modem invented,Modem,Technology,https://fiftiesweb.com/pop/inventions/,Communication between computers| foundation of...,1958
4,1960s,Statistician John Tukey defined data analysis,John Tukey / data analysis,People,https://projecteuclid.org/download/pdf_1/eucli...,Defined the process and procedures of collecti...,1961
5,1970s,"Dr. E.F. Codd creates concept of ""normalizing ...",Dr. EF Codd / normalized data,People,https://www.seas.upenn.edu/~zives/03f/cis550/c...,Made data independent from specific software /...,1970
6,1970s,FORTRAN Programing Language supports comma sep...,FORTRAN supports CSV Files,Technology,http://bitsavers.trailing-edge.com/pdf/ibm/370...,Programing Language can input / output data fi...,1972
7,1980s,Bloomberg Terminal Introduced,Mike Bloomberg / Terminal,Technology,https://www.bloomberg.com/company/press/timeli...,Financial Data Analysis of Bond Market to mark...,1982
8,1980s,"Edward Tufty writes the book ""The Visual Displ...",Edward Tufty / Data Viz concepts,People,https://www.amazon.com/gp/product/096139210X/r...,Defines ways to communicate with data beyond t...,1983
9,1980s,SQL Language Standardized across all database ...,SQL Standardized,Technology,https://blog.ansi.org/2018/10/sql-standard-iso...,A common language agnostic to technology for s...,1986
10,1980s,Microsoft Excel,MS Excel,Technology,https://en.wikipedia.org/wiki/Microsoft_Excel,Mainstream productivity software available to ...,1987
11,1980s,The term “BI (Business Intelligence)” was prop...,BI (Business Intelligence),Process,https://www.flydata.com/blog/a-brief-history-o...,Data becomes as Asset = used for analysis to m...,1989
12,1990s,On-Line Analytical Processing (OLAP) and Busin...,OLAP,Technology,http://dssresources.com/history/dsshistory.html,Data Volumes Increase| specialized software an...,1990
13,1990s,Guido van Rossum creates the Python programmin...,Guido van Rossum / Python,People,NaN,Programming language that has versility beyond...,1990
14,1990s,Finnish engineer Linus Torvalds introduces the...,Linus Torvalds / Linux OS,People,https://www.bloomberg.com/news/articles/2014-1...,Open Source software and Programming Languages...,1991
15,1990s,"Bill Inmon writes ""Building the data warehouse""",Bill Inmon / Data Warehouse,People,https://archive.org/details/buildingdataware00...,Organize data in a way to gain insights and an...,1993
16,1990s,QlikView software created,QlikView,Technology,NaN,Distruptive Technology that removes barriers f...,1993
17,1990s,"Ralph Kimball writes ""The data warehouse toolkit""",Ralph Kimball / Kimball Methodology,People,https://archive.org/details/datawarehousetoo00...,Enables growth of the data analyst and busines...,1996
18,1990s,XML Created,XML Created,Technology,https://en.wikipedia.org/wiki/XML,The goals of XML emphasize simplicity| general...,1996
19,1990s,The journal Data Mining and Knowledge Discover...,Data Mining defined,Process,https://www.forbes.com/sites/gilpress/2013/05/...,Evolving Data Mining as a skill moving away fr...,1997
20,1990s,Carlo Strozzi introduced the concept of NoSQL ...,Carlo Strozzi / NoSQL,People,https://en.wikipedia.org/wiki/NoSQL,Removed defined structures required by Relatio...,1998
21,2000s,REST / APIs,REST / APIs,Technology,https://en.wikipedia.org/wiki/Representational...,Data Democracy = If i can use a browser| I can...,2000
22,2000s,Natural Language Toolkit,Natural Language (NLP) Toolkit,Technology,https://en.wikipedia.org/wiki/Natural_Language...,statistical natural language processing (NLP) ...,2001
23,2000s,JSON was first presented to the world at the J...,JSON,Technology,http://www.ecma-international.org/publications...,Evolved from XML| data agnostic to the program...,2001
24,2000s,Stephen Few publishes Information Dashboard De...,Stephen Few,People,http://www.perceptualedge.com/articles/ie/the_...,Evolves data viz as a skill and effective mean...,2004
25,2000s,facebook,Facebook,Technology,https://en.wikipedia.org/wiki/Facebook,The Social Network influences people and data ...,2004
26,2000s,Google Analytics,Google Analytics,Technology,https://en.wikipedia.org/wiki/Google_Analytics,A web search engine and metadata (data about t...,2005
27,2000s,Apache Hadoop Big Data Storage Created,Apache Hadoop,Technology,https://en.wikipedia.org/wiki/Apache_Hadoop,The Data Lake offers alternatives to data mart...,2006
28,2000s,NumPy Library Introduced,NumPy,Technology,NaN,Python language library grows beyond programin...,2006
29,2000s,Twitter,Twitter,Technology,https://en.wikipedia.org/wiki/Twitter,Unstructured Big Data offers opportunities for...,2006
30,2000s,Amazon Web Services (AWS) S3 storage and intro...,AWS,Technology,https://en.wikipedia.org/wiki/Amazon_S3,Cloud computing = boundries to physical comput...,2006
31,2000s,GitHub,Github,Technology,https://github.com/about,Version control and sharing of code between te...,2007
32,2000s,Apple iPhone,iPhone,Technology,https://en.wikipedia.org/wiki/IPhone,Mobile Analytics becomes an industry,2007
33,2000s,pandas is a software library created,Pandas,Technology,https://en.wikipedia.org/wiki/Pandas_(software),Python evolves to the tool for open source dat...,2008
34,2000s,Uber Founded,Uber,Technology,https://en.wikipedia.org/wiki/Uber,Using Data and Technology to disrupt the trans...,2009
35,2010s,Kaggle.com created,Kaggle.com,Technology,https://en.wikipedia.org/wiki/Kaggle,Data Democracy in action = reward ANYONE who c...,2010
36,2010s,Naomi Robbins founds the Data Visualization Ne...,Naomi Robbins,People,https://www.meetup.com/DataVisualization/messa...,Pioneering Woman Engineer and Data Visualizati...,2011
37,2010s,Creation of the Raspberry PI,Raspberry PI,Technology,https://www.zdnet.com/article/technology-that-...,Making the IOT (Internet of Things) mass scale...,2012
38,2010s,"Alberto Cairo publishes the ""The Functional Ar...",Alberto Cairo,People,https://www.amazon.com/gp/product/B0091SXDOM/r...,Charts become an artform and careers like data...,2012
39,2010s,Project Jupyter,Jupyter Notebook,Technology,https://jupyter.org/,Open Source code and libraries becomes an all ...,2015
40,2010s,Amazon Alexa Ecosystem,Alexa,Technology,https://www.zdnet.com/article/technology-that-...,Making voice to data mainstream and allowing A...,2015
41,2010s,The Data Literacy Project launches,The Data Literacy Project,Process,https://www.businesswire.com/news/home/2018101...,Building a data driven culture where anyone ca...,2018

In [9]:
my_df.groupby(['Decade']).agg({'Year':'count'})

        Year
Decade
1940s      2
1950s      2
1960s      1
1970s      2
1980s      5
1990s      9
2000s     14
2010s      7